all:
	gcc -o tutorial01 tutorial01.c -lavutil -lavformat -lavcodec -lz -lavutil -lm -lpthread -ldl  -lswresample -lx264 -lswscale -lmp3lame   -lrt
	gcc -o tutorial02 tutorial02.c -lSDL2 -lavutil -lavformat -lavcodec -lz -lavutil -lm -lpthread -ldl  -lswresample -lx264 -lswscale -lmp3lame   -lrt
